[package]
name = "turbo-remote-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1"
env_logger = "^0.10"
log = "^0.4"
actix-files = "^0.6"
chrono = { version = "0.4", features = ["serde"] }
actix-cors = "^0.6"
dotenv = "^0.15"
futures-util = "^0.3"
object_store = {version = "^0.5", features=["aws", "azure", "gcp"]}
futures = "^0.3"
