version: 2.1

jobs:
  arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          command: |
            export DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            docker build -t salamaashoush/turbo-remote-cache-rs:latest-arm64 .
            docker push salamaashoush/turbo-remote-cache-rs:latest-arm64
  amd64:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            export DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            docker build -t salamaashoush/turbo-remote-cache-rs:latest-amd64 .
            docker push salamaashoush/turbo-remote-cache-rs:latest-amd64
  push:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run:
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            docker manifest create salamaashoush/turbo-remote-cache-rs:latest salamaashoush/turbo-remote-cache-rs:latest-arm64 salamaashoush/turbo-remote-cache-rs:latest-amd64
            docker manifest push salamaashoush/turbo-remote-cache-rs:latest

workflows:
  build-docker:
    jobs:
      - arm64:
          filters:
            branches:
              only: main
      - amd64:
          filters:
            branches:
              only: main
      - push:
          filters:
            branches:
              only: main
          requires:
            - arm64
            - amd64
