name: Release Crates

on:
  push:
    branches:
      - main
    paths:
      - Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release crates
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
